// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: koinos/contract_meta_store/contract_meta_store.proto

#include "koinos/contract_meta_store/contract_meta_store.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace koinos {
namespace contract_meta_store {
constexpr contract_meta_item::contract_meta_item(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : abi_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string){}
struct contract_meta_itemDefaultTypeInternal {
  constexpr contract_meta_itemDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~contract_meta_itemDefaultTypeInternal() {}
  union {
    contract_meta_item _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT contract_meta_itemDefaultTypeInternal _contract_meta_item_default_instance_;
}  // namespace contract_meta_store
}  // namespace koinos
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::koinos::contract_meta_store::contract_meta_item, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::koinos::contract_meta_store::contract_meta_item, abi_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::koinos::contract_meta_store::contract_meta_item)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::koinos::contract_meta_store::_contract_meta_item_default_instance_),
};

const char descriptor_table_protodef_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n4koinos/contract_meta_store/contract_me"
  "ta_store.proto\022\032koinos.contract_meta_sto"
  "re\"!\n\022contract_meta_item\022\013\n\003abi\030\001 \001(\tBEZ"
  "Cgithub.com/koinos/koinos-proto-golang/v"
  "2/koinos/contract_meta_storeb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto = {
  false, false, 196, descriptor_table_protodef_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto, "koinos/contract_meta_store/contract_meta_store.proto", 
  &descriptor_table_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto::offsets,
  file_level_metadata_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto, file_level_enum_descriptors_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto, file_level_service_descriptors_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto_getter() {
  return &descriptor_table_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto(&descriptor_table_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto);
namespace koinos {
namespace contract_meta_store {

// ===================================================================

class contract_meta_item::_Internal {
 public:
};

contract_meta_item::contract_meta_item(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:koinos.contract_meta_store.contract_meta_item)
}
contract_meta_item::contract_meta_item(const contract_meta_item& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  abi_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_abi().empty()) {
    abi_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_abi(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:koinos.contract_meta_store.contract_meta_item)
}

inline void contract_meta_item::SharedCtor() {
abi_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

contract_meta_item::~contract_meta_item() {
  // @@protoc_insertion_point(destructor:koinos.contract_meta_store.contract_meta_item)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void contract_meta_item::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  abi_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void contract_meta_item::ArenaDtor(void* object) {
  contract_meta_item* _this = reinterpret_cast< contract_meta_item* >(object);
  (void)_this;
}
void contract_meta_item::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void contract_meta_item::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void contract_meta_item::Clear() {
// @@protoc_insertion_point(message_clear_start:koinos.contract_meta_store.contract_meta_item)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  abi_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* contract_meta_item::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string abi = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_abi();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "koinos.contract_meta_store.contract_meta_item.abi"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* contract_meta_item::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:koinos.contract_meta_store.contract_meta_item)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string abi = 1;
  if (!this->_internal_abi().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_abi().data(), static_cast<int>(this->_internal_abi().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "koinos.contract_meta_store.contract_meta_item.abi");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_abi(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:koinos.contract_meta_store.contract_meta_item)
  return target;
}

size_t contract_meta_item::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:koinos.contract_meta_store.contract_meta_item)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string abi = 1;
  if (!this->_internal_abi().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_abi());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData contract_meta_item::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    contract_meta_item::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*contract_meta_item::GetClassData() const { return &_class_data_; }

void contract_meta_item::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<contract_meta_item *>(to)->MergeFrom(
      static_cast<const contract_meta_item &>(from));
}


void contract_meta_item::MergeFrom(const contract_meta_item& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:koinos.contract_meta_store.contract_meta_item)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_abi().empty()) {
    _internal_set_abi(from._internal_abi());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void contract_meta_item::CopyFrom(const contract_meta_item& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:koinos.contract_meta_store.contract_meta_item)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool contract_meta_item::IsInitialized() const {
  return true;
}

void contract_meta_item::InternalSwap(contract_meta_item* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &abi_, GetArenaForAllocation(),
      &other->abi_, other->GetArenaForAllocation()
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata contract_meta_item::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto_getter, &descriptor_table_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto_once,
      file_level_metadata_koinos_2fcontract_5fmeta_5fstore_2fcontract_5fmeta_5fstore_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace contract_meta_store
}  // namespace koinos
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::koinos::contract_meta_store::contract_meta_item* Arena::CreateMaybeMessage< ::koinos::contract_meta_store::contract_meta_item >(Arena* arena) {
  return Arena::CreateMessageInternal< ::koinos::contract_meta_store::contract_meta_item >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
