language: c++

cache:
  ccache: true

addons:
  apt:
    update: true
    packages:
      - clang
      - clang-format
      - llvm
      - llvm-dev
      - lcov
      - ruby
      - gcc-12
      - g++-12

env:
  global:
    - CMAKE_C_COMPILER_LAUNCHER=ccache
    - CMAKE_CXX_COMPILER_LAUNCHER=ccache

jobs:
  include:
    - name: "Static Analysis"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSTATIC_ANALYSIS=ON .
      script:
        - cmake --build . --config Debug --parallel 3

    - name: "Sanitizer"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      before_script:
        - sudo sysctl vm.mmap_rnd_bits=28 # https://stackoverflow.com/questions/77850769/fatal-threadsanitizer-unexpected-memory-mapping-when-running-on-linux-kernels
        - mkdir build-address
        - pushd build-address
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZER=Address ..
        - cmake --build . --config Debug --parallel 3
        - popd
        - mkdir build-stack
        - pushd build-stack
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZER=Stack ..
        - cmake --build . --config Debug --parallel 3
        - popd
        - mkdir build-thread
        - pushd build-thread
        - cmake -DCMAKE_BUILD_TYPE=Debug -DSANITIZER=Thread ..
        - cmake --build . --config Debug --parallel 3
        - popd
      script:
        - pushd build-address/tests
        - ctest -j1 --output-on-failure
        - popd
        - pushd build-stack/tests
        - ctest -j1 --output-on-failure
        - popd
        - pushd build-thread/tests
        - ctest -j1 --output-on-failure

    - name: "Coverage"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      install:
        - sudo gem install coveralls-lcov
      before_script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON ..
      script:
        - cmake --build . --config Debug --parallel 3 --target coverage
      after_success:
        - coveralls-lcov --repo-token $COVERALLS_REPO_TOKEN --service-name travis-pro --service-job-id $TRAVIS_JOB_ID ./coverage.info

    - name: "GCC Unit Tests"
      os: linux
      dist: jammy
      env:
        - CC=gcc-12
        - CXX=g++-12
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
        - cmake --build . --config Release --parallel 3
      script:
        - cd tests
        - ctest -j3 --output-on-failure

    - name: "Clang Unit Tests and Formatting"
      os: linux
      dist: jammy
      env:
        - CC=clang
        - CXX=clang++
      before_script:
        - cmake -DCMAKE_BUILD_TYPE=Release .
        - cmake --build . --config Release --parallel 3
      script:
        - cmake --build . --config Release --parallel 3 --target format.check
        - cd tests
        - ctest -j3 --output-on-failure

notifications:
  slack:
    secure: ErBI1W7SR9lK/ZFfy62NONogHMaq2q+gxICi0OP5kP4wm+wFftrNnH1yJaqwbhzyKW+nwBCyq4xO3s9D0AC4LHI5JczzsW6KDgf0/rVlNTaRHTn4xHvnjsKSTTUsisM1umy0h9S7NcnGsmqKtkgeSXg8lhcYyN3Dich+zqVPQtrtX5ecjaNe75/tz/2Addj2BZ3yb4tLv/uyzqhLCDvFoO6vYrFwYf9puozKCiN+8ZuT/SLV+4hcgqzx1C82hMYbzrr+cxHbEIjG+OZzF32mTZ2JxgNxuB25hIi23nywWm9HO2vQavD3i97+WVyZkG/44aItytx6Cr1fvyadVVEvnBRa+k04+gDFrBVNcccRZiREc21SpJOaICYrOPQH1Xpi0UBnKu28l12kmL95QgZD70h3sThjzXNXknUYg1RFZeYoatJCbl32nkBlCvajrVJCbwIIoH7xJ5gkzN46dIOTdwthIz9sagNEQhcLuErulOFts4SYZUKIeHLhQH2LUB6mRUsNswyYffGy2JGAxMrwhse5tROI4c+/59fsx3dUNuQGSwJViM7XkDQhFGR5Ybn3gEPHhxI6eb798bcCfu/ac4r4vBFg/P/O7FOfYcO2IKfa+Fxj/LS10vwUO2+LnlQ4nAcuwZ8+NgQ1QL+uGFrcq8PbnxO0MqYcpa1Dehc6hqw=
    on_success: never
